name: 'Get Tag Name'
inputs:
  artifact_name:  # id of input
    type: string
    required: true
runs:
  using: "composite"
  steps:
    - name: Test name
      run: echo ${{ inputs.artifact_name }}
    - name: Download Data Artifact
      uses: actions/download-artifact@v3
      with:
        name:  ${{ inputs.artifact_name }}
        path:  ${{ inputs.artifact_name }}
    - name: Set tag env
      run: |
        TAG=$(head -n 1 workspace/vars.txt)
        echo "TAG=$TAG" >> $GITHUB_ENV
        echo $TAG
      shell: bash
