# This is a basic workflow to help you get started with Actions
name: Connect to an AWS role from a GitHub repository
on: workflow_dispatch

env:
  AWS_REGION : us-east-1

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::087229364167:role/GitHubAction-AssumeRoleS3ReadOnly
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
      - name: List S3 Buckets
        run: aws s3 ls
