name: Push Release
on:
  workflow_dispatch:
    inputs:
      production:
        type: boolean
        description: 'Production?'
        default: true
  push:
    branches:
      - 'release/*'

env:
  PRODUCTION: 'bridge-job'
  # PRODUCTION: ${{ github.event_name != 'workflow_dispatch' && 'true' || inputs.production }}
  

jobs:
  bridge-job:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name != 'master' }}
    steps:
      - run: echo "placeholder"
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: ${{ env.PRODUCTION}}
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ env.PRODUCTION == 'true' && '--production' || '' }}
