name: Deploy-Actions
on: push

env:
  PORT: 3000
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: create a workspace
        run: mkdir -p workspace
      - name: Build Image
        run: |
          TAG=$(date +%Y.%m.%d-%H.%M) && echo "export TAG='${TAG}'" &&
          docker build --build-arg PORT=${PORT} -t kk-ms:latest .
      - name: Persist Image
        run: |
          docker save -o workspace/mailsender_image kk-ms:latest
      - name: Upload Data Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-image
          path: workspace/mailsender_image
          retention-days: 1
          
  unit-test:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Download Data Artifact
        uses: actions/download-artifact@v2
        with:
          name: build-image
          path: workspace
      - name: Get docker image
        run: docker load -i workspace/mailsender_image
      - name: run unit test
        run: docker run -t --entrypoint npm kk-ms:latest run test
  push-to-ecr:
    environment: prod
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Download Data Artifact
        uses: actions/download-artifact@v2
        with:
          name: build-image
          path: workspace
      - name: Get docker image
        run: docker load -i workspace/mailsender_image
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a
