name: Deploy-Actions
on: push
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "unit test passed"
  deploy:
    environment: prod
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: 
        run: exit 1
