name: Deploy-Actions
on: push

env:
  PORT=3000
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - run: |
          TAG=$(date +%Y.%m.%d-%H.%M) && echo "export TAG='${TAG}'" &&
          docker build --build-arg PORT=${PORT} -t kk-ms:${TAG} .
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "unit test passed"
  deploy:
    environment: prod
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: 
        run: exit 1
