name: Impact Agent

on:
  workflow_dispatch:
    inputs:
     Agent:
        type: choice
        description: 'Do you want to run Impact agent'
        required: true
        default: no
        options:
        - yes
        - no

jobs:
  review_bot:
    name: Impact places
    runs-on: ubuntu-latest
    timeout-minutes: 8
    environment: test
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0