name: Main-Actions
on: push
env:
  DEPENDENT_JOB: ${{ github.ref_name == 'master' }}
jobs:
  bridge-job:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name != 'master' }}
    steps:
      - run: echo "placeholder"
  job2:
    runs-on: ubuntu-latest
    needs: ${{ github.ref_name != 'master' && 'bridge-job' || [] }}
    if: ${{ github.ref_name == 'master' || needs.job1.outputs.output1 == 'hello' }}
    steps:
      - run: echo "Do something"
