name: Main-Actions
on: push
jobs:
  job-1:
    if: ${{ github.ref_name != 'master' }}
    runs-on: ubuntu-latest
    outputs:
      validation_result: ${{ steps.validate_branch_name.outputs.validation_result }}
    env:
      BRANCH_VALIDATION_RESULT: ${{ steps.validate_branch_name.outputs.validation_result }}
    steps:
    - name: Validate branch name
      run: |
        echo "::set-output name=validation_result::success"
        echo "BRANCH_VALIDATION_RESULT=success"
    - name: Print the value - Job-1
      run: echo "This is 1st Job"

  job-2:
    needs: job-1
    runs-on: ubuntu-latest
    if: needs.job-1.outputs.validation_result == 'success' || needs.job-1.outputs.validation_result == 'skipped' || env.BRANCH_VALIDATION_RESULT == 'success' || env.BRANCH_VALIDATION_RESULT == 'skipped'
    steps:
    - name: Print the value - Job-2
      run: |
        echo "Outputs: ${{ needs.job-1.outputs.validation_result }}"
        echo "Environment: $BRANCH_VALIDATION_RESULT"
    - uses: actions/checkout@v3
