name: Mixed inputs

env:
  BRANCH: ${{ toJson(github) }}
  
on:
  workflow_dispatch:
    inputs:
      userpickerName:
        description: 'Enter the userpicker name'
      mailSenderName:
        description: 'Enter the mailsender name'
      baseUrl:
        description: 'Enter the server BaseURL'
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: print the Userpicker
      run: echo $BRANCH
    - name: print branchname
      run: echo "BRANCH_NAME=${{ github.ref_name }}-${{ github.event.head_commit.timestamp }}" >> $GITHUB_ENV
    - name:  print the env
      run: echo $BRANCH_NAME
