name: Mixed inputs

env:
  PUSHED_TIME: ${{ github.pushed_at }}
  BRANCH_NAME: ${{ github.ref_name - github.pushed_at }}
  
on:
  workflow_dispatch:
    inputs:
      userpickerName:
        description: 'Enter the userpicker name'
      mailSenderName:
        description: 'Enter the mailsender name'
      baseUrl:
        description: 'Enter the server BaseURL'
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: print the Userpicker
      run: echo ${{ github.event.inputs.userpickerName }}
    - name: print the Mailsender
      run: echo ${{ github.event.inputs.mailSenderName }}
    - name: print the BaseURL
      run: echo ${{ github.event.inputs.baseUrl }}
    - name: print branchname
      run: echo $BRANCH_NAME
