name: Main-Actions
on: push
jobs:
  bridge-job:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name != 'master' }}
    steps:
      - run: echo "placeholder"
  job2:
    runs-on: ubuntu-latest
    if: always()
    needs: bridge-job
    steps:
      - name: fail if conditional job failed
        if: ${{ needs.bridge-job.result == 'failure' }}
        run: exit 1
      - run: echo "Do something"
