name: Main-Actions
on: push
jobs:
  job-1:
    if: always() == false
    runs-on: ubuntu-latest
    outputs:
      validation_result: ${{ steps.step1.outputs.validation_result }}
    steps:
    - id: step1
      name: Validate branch name
      run: |
        echo "validation_result=success" >> "$GITHUB_OUTPUT"
    - name: Print the value - Job-1
      run: echo "This is 1st Job"
  job-2:
    needs: job-1
    runs-on: ubuntu-latest
    if: always() || needs.validate-branch-name.result == 'skipped' 
    steps:
    - name: Print the value - Job-2
      run: |
        echo "Outputs: ${{ needs.job-1.outputs.validation_result }}"
    - name: Checkout code
      uses: actions/checkout@v3
