name: Main-Actions
on: push
jobs:
  set-job:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: echo "test=job-1" >> "$GITHUB_OUTPUT"
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: print the value  - Job-1
        run: echo "This is 1st Job"

  job-2:
    env:
      OUTPUT1: ${{needs.job1.outputs.output1}}
    needs: ${{env.OUTPUT1}}
    runs-on: ubuntu-latest
    steps:
      - name: print the value - Job-2
        run: echo "This is 2nd Job"
      - uses: actions/checkout@v3

