name: test on multiple runners

on:
  push:
    branches:
      - master
      - test

jobs:
  simple-test:
    # if affected branch is 'test' then runs on 'ubuntu-latest' else self-hosted...
    runs-on: ${{ github.ref_name == 'test' && 'ubuntu-latest' || fromJSON('["self-hosted", "products", "latest"]') }}
    steps:
      - name: simple evaluation on test
        run: echo "runs"
