name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      use-emoji:
        type: boolean
        description: Run Cypress test

jobs:
  greet:
    runs-on: ubuntu-latest
    # if: github.event.inputs.use-emoji == true
    steps:
    - name: print the input
      run: echo ${{ github.event.inputs.use-emoji }}
    - name: Send greeting
      run: echo "true print"
