name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Enter the function name'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: print the input
      run: echo ${{ github.event.inputs.message }}

