name: Main-Actions
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name != 'master' && github.event_name != 'schedule'}}
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - name: Print the value - Job-1
        run: echo "This is 1st Job"
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: []
    if: ${{needs.validate-branch-name.outputs.output1 == 'hello' || github.ref_name == 'master' || github.event_name == 'schedule'}}
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
        run: echo "$OUTPUT1"
