name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      dst:
        description: Select checkbox
      cypressInput:
        type: boolean
        description: 'Do you want to run cypress test ?'
        required: true
      unitTestInput:
        type: boolean
        description: 'Do you want to run unit test'
      slackInput:
        type: boolean
        description: 'Do you want slack report for cypress test'

jobs:
  greet:
    runs-on: ubuntu-latest
    # if: github.event.inputs.use-emoji == true
    steps:
    - name: print the input
      run: echo ${{ github.event.inputs.use-emoji }}
    - name: Send greeting
      run: echo "true print"
