name: Main-Actions
on: push
jobs:
  job-1:
    if: ${{ github.ref_name != 'master' }}
    runs-on: ubuntu-latest
    steps:
      - name: print the value  - Job-1
        run: echo "This is 1st Job"

  job-2:
    if: needs.job-1.result == 'skipped'
    # needs: job-1
    runs-on: ubuntu-latest
    steps:
      - name: print the value - Job-2
        run: echo "This is 2nd Job"
      - uses: actions/checkout@v3

