name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Select the checkbox'
      cypressInput:
        type: boolean
        description: 'Run Cypress Test'
      unitTestInput:
        type: boolean
        description: 'Run Unit Test'
      slackInput:
        type: boolean
        description: 'Slack report for cypress test'

jobs:
  greet:
    runs-on: ubuntu-latest
    # if: github.event.inputs.use-emoji == true
    steps:
    - name: print the input
      run: echo ${{ github.event.inputs.use-emoji }}
    - name: Send greeting
      run: echo "true print"

  run-cypress-test-1:
    needs: greet
    name: run-cypress-test (1)
    runs-on: ubuntu-latest
    if: "!cancelled() && github.ref_name == 'master' && github.event.inputs.cypressInput == true"
    steps:
      - name: Print the message
        run: echo hi

