name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      cypressInput:
        type: boolean
        description: 'Run Cypress Test'
      unitTestInput:
        type: boolean
        description: 'Run Unit Test'
      slackInput:
        type: boolean
        description: 'Slack report for cypress test'

jobs:
  greet:
    runs-on: ubuntu-latest
    # if: github.event.inputs.use-emoji == true
    steps:
    - name: print the input
      run: echo ${{ github.event.inputs.use-emoji }}
    - name: Send greeting
      run: echo "true print"
