name: Mixed inputs

env:
  BRANCH: ${{ toJson(github) }}
  
on:
  workflow_dispatch:
    inputs:
      userpickerName:
        description: 'Enter the userpicker name'
      mailSenderName:
        description: 'Enter the mailsender name'
      baseUrl:
        description: 'Enter the server BaseURL'
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Repo Name
      run: echo ${{ github.event.repository.name }}
    - name: print the Userpicker
      run: echo $BRANCH
    - name: print branchname
      run: echo "BRANCH_NAME=${{ github.ref_name }}-${{ github.event.repository.pushed_at }}" >> $GITHUB_ENV
    - name:  print the env
      run: echo $BRANCH_NAME
  greet1:
    runs-on: ubuntu-latest
    needs: greet
    steps:
    - name:  print the env
      run: echo $BRANCH_NAME
  greet2:
    runs-on: ubuntu-latest
    needs: greet1
    steps:
    - name:  print the env
      run: echo $BRANCH_NAME
