name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      use-emoji:
        type: boolean
        description: want to run greet 

jobs:
  greet:
    runs-on: ubuntu-latest
    if: github.event.inputs.use-emoji == true
    steps:
    - name: Send greeting
      run: echo "true print"
