name: Main-Actions
on: push
jobs:
  job-1:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name != 'master' || github.event_name != 'schedule' || github.event.inputs.optionInput == 'yes' }}
    outputs:
      validation_result: ${{ steps.step1.outputs.validation_result }}
    steps:
      - id: step1
        name: Validate branch name
        run: |
          if [[ "${GITHUB_HEAD_REF}" != "master" ]]; then
            echo "validation_result=failed" >> "$GITHUB_OUTPUT"
            exit 1
          else
            echo "validation_result=success" >> "$GITHUB_OUTPUT"
          fi
      - name: Print the value - Job-1
        run: echo "This is 1st Job"
  job-2:
    needs: job-1
    runs-on: ubuntu-latest
    if: needs.job-1.result == 'success' || needs.job-1.result == 'skipped'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
