name: Main-Actions
on: push
env:
  DEPENDENT_JOB: ${{ github.ref_name == 'master' }}
jobs:
  job1:
    runs-on: ubuntu-latest
    if: ${{ env.DEPENDENT_JOB == 'true' }}
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - name: Print the value - Job-1
        run: echo "This is 1st Job"
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: ${{ env.DEPENDENT_JOB && ['job1'] || [] }}
    if: ${{ github.ref_name == 'master' || needs.job1.outputs.output1 == 'hello' }}
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
        run: echo "$OUTPUT1"
