name: Main-Actions
on: push
jobs:
  job-1:
    runs-on: self-hosted
    steps:
      - name: print the value  - Job-1
        run: echo "This is 1st Job"

  job-3:
    needs: job-1
    runs-on: ubuntu-latest
    steps:
      - name: print the value - Job-2
        run: echo "This is 2nd Job"
      - uses: actions/checkout@v3
  jobs-4:
    needs: job-3
    uses: ./.github/workflows/reuseable.yml
