name: Matrix Jobs Example

on: [push]

env:
  PARALLELISM: 5

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.BRANCH_NAME }}
    steps:
      - id: step1
        run: |
          BRANCH_NAME=$(bash ./.github/scripts/generateTestTag.sh TEST-1234/actionS) 
          echo $BRANCH_NAME
          echo "BRANCH_NAME=BRANCH_NAME" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
        run: echo "$OUTPUT1 $OUTPUT2"
