name: Matrix Jobs Example

on:
  push:
    paths-ignore:
      - "server/*.sh"
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.branch_name.outputs.BRANCH_NAME }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Getting Git-Sha Value
        run: GIT_SHA=$(git rev-parse --short HEAD) && echo "GIT_SHA=$GIT_SHA" >> "$GITHUB_ENV"

      - name: Print Git SHA
        run: echo "Git SHA is ${{ env.GIT_SHA }}"
      - name: Get branch name
        id: branch_name
        run: |
          bash ./.github/scripts/generateTestTag.sh TEST-1234/actionS
        shell: bash 
      - name: Use the branch name in another job
        run: echo ${{ steps.branch_name.outputs.BRANCH_NAME }}
  job2:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      output2: ${{ steps.branch_name_tag.outputs.BRANCH_NAME_TAG }}
    steps:
      - name: Get branch name
        id: branch_name_tag
        run: |
          echo "BRANCH_NAME_TAG=${{ needs.build.outputs.output1 }}" >> "$GITHUB_OUTPUT"
          echo $BRANCH_NAME_TAG
        shell: bash 
      - name: Use branch name in job2
        run: |
          echo "Branch name in job2: ${{ needs.build.outputs.output1 }}"
  job3:
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - name: Use the branch name in another job
        run: echo ${{ needs.job2.outputs.output2 }}
