name: Matrix Jobs Example

on: [push]

env:
  PARALLELISM: 5
jobs:
  runner-indexes:
    runs-on: ubuntu-latest
    name: Parallelism
    outputs:
      json: ${{ steps.generate-index-list.outputs.json }}
    steps:
      - id: generate-index-list
        run: |
          MAX_INDEX=$((${{ env.PARALLELISM }}-1))
          INDEX_LIST=$(seq 0 ${MAX_INDEX})
          INDEX_JSON=$(jq --null-input --compact-output '. |= [inputs]' <<< ${INDEX_LIST})
          echo "json=${INDEX_JSON}" >> "$GITHUB_OUTPUT"
  automation-test:
    needs: [runner-indexes]
    runs-on: ubuntu-latest
    name: 'automation-test'
    strategy:
      fail-fast: false
      matrix:
        runner-index: ${{ fromjson(needs.runner-indexes.outputs.json) }}
    steps:
      - name: Print the jobName
        run: echo ${{ github.job }} # Will only return the job_id: "my-job"
      - name: TEST
        run: |
          JOB_NAME="OS ${{ matrix.os }}"
          echo $JOB_NAME
          echo "JOB_NAME=$JOB_NAME" >> $GITHUB_ENV=
      - name: Print JOB_NAME
        run: |
          echo "JOB NAME:" ${{ env.JOB_NAME }}
      - name: Checkout Branch
        uses: actions/checkout@v3
      - name: print the output
        run: echo ${{ needs.runner-indexes.outputs.json }}

  
