name: Matrix Jobs Example

on: [push]

env:
  PARALLELISM: 5

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Get branch name
        id: branch_name
        run: |
          BRANCH_NAME=$(bash ./.github/scripts/generateTestTag.sh TEST-1234/actionS)
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

  job2:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Use branch name in job2
        run: |
          echo "Branch name in job2: $BRANCH_NAME"

  job3:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Use branch name in job3
        run: |
          echo "Branch name in job3: $BRANCH_NAME"

  job4:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Use branch name in job4
        run: |
          echo "Branch name in job4: $BRANCH_NAME"
