name: Matrix Jobs Example

on: [push]

env:
  PARALLELISM: 5
jobs:
  runner-indexes:
    runs-on: ubuntu-latest
    name: Parallelism
    outputs:
      json: ${{ steps.generate-index-list.outputs.json }}
    steps:
      - id: generate-index-list
        run: |
          MAX_INDEX=$((${{ env.PARALLELISM }}-1))
          INDEX_LIST=$(seq 0 ${MAX_INDEX})
          INDEX_JSON=$(jq --null-input --compact-output '. |= [inputs]' <<< ${INDEX_LIST})
          echo "json=${INDEX_JSON}" >> "$GITHUB_OUTPUT"
  automation-test:
    needs: [runner-indexes]
    runs-on: ubuntu-latest
    name: 'automation-test'
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     runner-index: ${{ fromjson(needs.runner-indexes.outputs.json) }}
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      - name: print the output
        run: echo ${{ needs.runner-indexes.outputs.json }}
      # - uses: chaosaffe/split-tests@v1-alpha.1
      #   id: split-tests
      #   name: Split tests
      #   with:
      #     glob: cypress/e2e/**/*.cy.js
      #     split-total: ${{ env.PARALLELISM }}
      #     split-index: ${{ matrix.runner-index }}
      #     junit-path: junit/*.xml
      # - run: |
      #     echo "TEST=${{ steps.split-tests.outputs.test-suite }}" >> $GITHUB_ENV
  
