name: KK-Lab
on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:
    inputs:
      optionInput:
        description: 'Do you want to run cypress test ?'
        required: true
        default: 'yes'
        options: ['yes', 'no']

concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true


jobs:
  validate-branch-name:
    if: ${{ github.ref_name != 'master' && github.event_name != 'schedule' && github.event.inputs.optionInput == 'yes' }}
    environment: test
    runs-on: ubuntu-latest
    name: Validate Branch Name
    steps:
      - name: Validate Branch Name
        run: echo "validate-branch-name"

  runner-indexes:
    needs: []
    environment: test
    runs-on: ubuntu-latest
    if: always()
    name: Generate parallelism
    outputs:
      json: ${{ steps.generate-index-list.outputs.json }}
    steps:
      - name: Checking Validate branch Name status
        if: ${{ needs.validate-branch-name.result == 'failure' }}
        run: exit 1
      - id: generate-index-list
        run: |
          MAX_INDEX=$((${{ env.parallelism }}-1))
          INDEX_LIST=$(seq 0 ${MAX_INDEX})
          INDEX_JSON=$(jq --null-input --compact-output '. |= [inputs]' <<< ${INDEX_LIST})
          echo "json=${INDEX_JSON}" >> "$GITHUB_OUTPUT"

  create-actions-runner:
    needs: runner-indexes
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: check create-actions-runner
        run: echo "create-actions-runner"

  run_cypress_tests:
    needs: [runner-indexes, create-actions-runner]
    environment: test
    runs-on: ubuntu-latest
    name: 'Runner-${{ github.run_id }}-${{ matrix.runner-index }}'
    strategy:
      fail-fast: false
      matrix:
        runner-index: ${{ fromjson(needs.runner-indexes.outputs.json) }}
    steps:
      - name: Archive Cypress screenshots
        run: echo "Testing"
  slack-report:
    needs: [run_cypress_tests]
    environment: test
    runs-on: ubuntu-latest
    name: Send Slack report
    if: ${{ github.event_name == 'schedule' }}
    steps:
      - name: Send report to Slack
        run: echo "Sending slack report"
  cleanup_resources:
    environment: test
    runs-on: ubuntu-latest
    needs:
      [runner-indexes, create-actions-runner, run_cypress_tests, slack-report]
    if: always()
    steps:
      - name: Clean up any resources created for the job
        run: echo "Deletion of ACIs completed."
