name: Rerun-Test

on: workflow_dispatch

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Print event name
        run: |
          echo "event name is:" ${{ github.event_name }} 
          echo "event type is:" ${{ github.event.action }} 
      - name: Fail this step
        run: exit 1
