name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  LABEL_NAME: Runner-${{ github.run_id }}
jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ env.LABEL_NAME }}
    steps:
    - id: runner
      run: echo test

  test:
    needs: [build]
    runs-on: ${{ needs.build.outputs.runner }}
    steps:
      - run: echo I Ran
