name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  LABEL_NAME: Runner-${{ github.run_id }}
jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ env.LABEL_NAME }}
    steps:
    - id: runner
      run: echo test
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.build.outputs.runner }}
  test1:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.build.outputs.runner }}
  test2:
    needs: [test1]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.build.outputs.runner }}
  test3:
    needs: [test2]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.build.outputs.runner }}
