name: Rerun-Test

on: workflow_dispatch
env:
  LABEL_NAME: Runner-${{ github.run_id }}
jobs:
  job-name:
    runs-on: $LABEL_NAME
    steps:
      - name: Print event name
        run: |
          echo $LABEL_NAME
          echo "event name is:" ${{ github.event_name }} 
          echo "event type is:" ${{ github.event.type }} 
      - name: Fail this step
        run: exit 1
