name: My reusable job

on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: print the value - Job-2
        run: echo "This is 2nd Job"
      - name: Branch Name
        run: echo Branch Name ${{ github.ref_name }}
      - name: Clear cache
        run: |
          echo "Clearing cache..."
          rm -rf ~/.cache/actions/*