name: Reusebale-Unit-Test
on:
  workflow_call:
    inputs:
      artifact_name:
        type: string
        required: true

jobs:
  unit-test:
    runs-on: kk-ms
    steps:
      - name:  Get the tag
        uses: ./.github/actions/getTagName
      - name: Unit test run
        run: docker images
      - name: Unit test run
        run: docker run --entrypoint npm kk-ms:${{env.TAG}} run test
          