name: Reuseable-Workflow
on:
  workflow_call:
    inputs:
      artifact_name:
        type: string
        required: true

env:
  PORT: 3000
jobs:
  build-image:
    runs-on: kk-ms
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name:  Get the tag
        uses: ./.github/actions/getTagName
      - name: Build image
        run: docker build --build-arg PORT=${{env.PORT}} -t kk-ms:${{env.TAG}} .