name: Reusebale-Unit-Test
on:
  workflow_call:
    inputs:
      artifact_name:
        type: string
        required: true

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Download Data Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{inputs.artifact_name}}
          path: ${{inputs.artifact_name}}
      - name: Set tag env
        run: |
          TAG=$(head -n 1 workspace/vars.txt)
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo $TAG
      - name: Unit test run
        run: docker run --entrypoint npm kk-ms:${{env.TAG}} run test
          