name: Reuseable-Workflow
on: workflow_call

env:
  PORT: 3000
jobs:
  build-image:
    runs-on: ${{ github.ref_name == 'master' && 'ubuntu-latest' || fromJSON('["kk-ms"]') }}
    steps:
      - name: Check env name
        run:  echo ${{inputs.tag}}
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name:  Get the tag
        uses: ./.github/actions/getTagName
      - name: Build image
        run: docker build --build-arg PORT=${{env.PORT}} -t kk-ms:${{env.TAG}} .