name: Reuseable-Workflow
on:
  workflow_call:
    inputs:
      job_to_run:
        type: string
        required: false
      tag_name:
          type: string
          required: true
    # outputs:
    #   result:
    #     value: ${{ jobs.build-image.outputs.output1 }}

env:
  PORT: ${{ vars.ENV }}

jobs:
  build-image:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: create a workspace
        run: mkdir -p workspace
      - name: Print ENV
        run: echo ${PORT}
      - name: Build Image
        run: |
          docker build --build-arg PORT=${PORT} -t kk-ms:latest .
      - name: Checking the tag name
        run: echo ${{inputs.tag_name}}
      - name: Persist Image
        run: |
          docker save -o workspace/mailsender_image kk-ms:latest
      - name: Upload Data Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-image
          path: workspace/mailsender_image
          retention-days: 1