name: test

on: workflow_dispatch

jobs:
  runner-indexes:
    runs-on: ubuntu-latest
    name: Print the repo name
    steps:
      - name: print the repo name
        run: echo ${{ github.event.repository.name }}
