name: test

on: 
  workflow_dispatch:
    inputs:
      cypressInput:
        type: boolean
        description: 'Run Cypress Test'
      unitTestInput:
        type: boolean
        description: 'Run Unit Test'
      slackInput:
        type: boolean
        description: 'Slack report for cypress test'
env:
  NO_OF_INSTANCES: ${{ inputs.cypressInput == true && 7 ||  inputs.unitTestInput == true && 1 || 8 }}
  
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Value
        run: |
          if [ ${{ inputs.cypressInput  == 'true' }}]; then
            echo 7
          elif [ ${{ inputs.unitTestInput == 'true' }}  ]; then
            echo 1
          else
            echo 8
          fi

