name: test-Lab

on: push

env:
  PR_NUMBER: ${{ github.event.number }}
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print the PR number for testing
        run: echo "PR_NUMBER" $PR_NUMBER