name: test-github-Actions
on: push
jobs:
  job-1:
    if: ${{github.ref_name != 'master'}}
    runs-on: ubuntu-latest
    steps:
      - name: print the value  - Job-1
        run: echo "This is 1st Job"
  temp:
    if: ${{github.ref_name == 'master'}}
    runs-on: ubuntu-latest
    steps:
      - name: print the value  - Job-1
        run: echo "This is 1st Job"
  job-2:
    if: ${{github.ref_name != 'master'}}
    needs: job-1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Call reusable job
        uses: ././reuseable.yml

  job-3:
    needs: job-2
    runs-on: ubuntu-latest
    steps:
      - name: print the value - Job-3
        run: echo "This is 3rd Job"
