name: test

on: workflow_dispatch

jobs:
  test-job-1:
    runs-on: ubuntu-latest
  steps:
    runs-on: ubuntu-latest
    name: test-upload Artifact
    steps:
      - name: Print the repo name
        uses: echo ${{ github.event.repository.name }}
