name: test

on: 
  workflow_dispatch:
    inputs:
      cypressInput:
        type: boolean
        description: 'Run Cypress Test'
      unitTestInput:
        type: boolean
        description: 'Run Unit Test'
      slackInput:
        type: boolean
        description: 'Slack report for cypress test'
env:
  NO_OF_INSTANCES: ${{ inputs.cypressInput == true && 7 ||  inputs.unitTestInput == true && 1 || 8 }}
  
jobs:
  my_job:
    runs-on: ubuntu-latest
    environment: test
    outputs:
      json: ${{ steps.generate-index-list.outputs.json }}
    steps:
      - name: Checking
        run: echo ${{vars.CYPRESS_INSTANCE_COUNT}}
      - id: generate-index-list
        run: |
          if [ ${{ inputs.cypressInput }} == true && ${{ inputs.unitTestInput }} == true ]; then
            echo json=8 >> "$GITHUB_OUTPUT"
          elif [ ${{ inputs.unitTestInput }} == true ]; then
            echo json=${{vars.UT_INSTANCE_COUNT}} >> "$GITHUB_OUTPUT"
          elif [ ${{ inputs.cypressInput }} == true ]; then
            echo json=${{vars.CYPRESS_INSTANCE_COUNT}} >> "$GITHUB_OUTPUT"
          fi
  my_job-1:
    runs-on: ubuntu-latest
    environment: test
    needs: my_job
    steps:
      - name: Echo Value
        run: echo ${{ needs.my_job.outputs.json }}
