name: test

on: 
  workflow_dispatch:
    inputs:
      cypressInput:
        type: boolean
        description: 'Run Cypress Test'
      unitTestInput:
        type: boolean
        description: 'Run Unit Test'
      slackInput:
        type: boolean
        description: 'Slack report for cypress test'
env:
  NO_OF_INSTANCES: |
    ${{ if eq(inputs.cypressInput, true) }}${{ vars.CYPRESS_INSTANCE_COUNT }}
    ${{ else if eq(inputs.unitTestInput, true) }}${{ var.UT_INSTANCE_COUNT }}
    ${{ else }}8
    ${{ endif }}

  
jobs:
  runner-indexes:
    runs-on: ubuntu-latest
    name: Print the repo name
    steps:
      - name: print the repo name
        run: echo ${{ github.event.repository.name }}
      - name: print the repo name
        run: echo ${{ github.actor }}
      - name: print the check
        run: echo ${{env.NO_OF_INSTANCES}}
