name: test-Lab

on: workflow_dispatch

env:
  RUN_ID:  ${{ github.run_id }}
  ORG: ${{ secrets.ORG }}
  REPO: ${{ secrets.REPO }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  test-job:
    runs-on: ubuntu-latest
    name: print Run ID
    steps:
      - name: Print the current run id
        run: echo "PR_NUMBER" $RUN_ID
      - name: custom actions
        id: custom-action
        uses: iamkishorekumar-git/GetWorkflowJobsStatus@v.11
        with:
          ORG: $ORG
          REPO: $ORG
          RUN_ID: ${{ github.run_id }}
          JOB_NAME: unit-test-job, cypress-run-job
      - name: Use Custom Action Output
        run: echo ${{ steps.custom-action.outputs.my_output }}


  # unit-test:
  #   runs-on: ubuntu-latest
  #   name: unit-test-job
  #   steps:
  #     - name: run unit test
  #       run: echo "Running unit test"
    
