name: test-Lab

on: workflow_dispatch

env:
  RUN_ID:  ${{ github.run_id }}
  ORG: ${{ secrets.ORG }}
  REPO: ${{ secrets.REPO }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  JOB_NAME_1: unit-test-job
  JOB_NAME_2: cypress-test-job
  CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  
  
jobs:


  unit-test:
    runs-on: ubuntu-latest
    name: unit-test-job
    steps:
      - name: run unit test
        run: exit 1
        
  cypress-test:
    needs: unit-test
    if: always()
    runs-on: ubuntu-latest
    name: cypress-test-job
    steps:
      - name: run unit test
        run: exit 0
    
  test-job:
    needs: [unit-test,cypress-test]
    if: always()
    runs-on: ubuntu-latest
    name: print Run ID
    steps:
      - name: Print the current run id
        run: echo "PR_NUMBER" $RUN_ID
      - name: custom actions
        id: custom-action
        uses: iamkishorekumar-git/GetWorkflowJobsStatus@v0.3
        with:
          ORG: $ORG
          REPO: $ORG
          RUN_ID: ${{ github.run_id }}
          CHANNEL_ID: $CHANNEL_ID
          SLACK_BOT_TOKEN: $SLACK_BOT_TOKEN
      - name: Use Custom Action Output
        run: echo ${{ steps.custom-action.outputs.my_output }}
