name: test-Lab

on: workflow_dispatch

env:
  RUN_ID:  ${{ github.run_id }}
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print the current run id
        run: echo "PR_NUMBER" $RUN_ID
