name: test

on: 
  workflow_dispatch:
    inputs:
      cypressInput:
        type: boolean
        description: 'Run Cypress Test'
      unitTestInput:
        type: boolean
        description: 'Run Unit Test'
      slackInput:
        type: boolean
        description: 'Slack report for cypress test'
env:
  NO_OF_INSTANCES: ${{ inputs.cypressInput == true && 7 ||  inputs.unitTestInput == true && 1 || 8 }}
  
jobs:
  my_job:
    runs-on: ubuntu-latest
    environment: test
    outputs:
      json: ${{ steps.generate-index-list.outputs.json }}
    steps:
      - id: generate-index-list
        run: |
          SUM=$(( ${{vars.UT_INSTANCE_COUNT}} + ${{vars.CYPRESS_INSTANCE_COUNT}} ))
          if [ "${{ inputs.cypressInput }}" == true ] && [ "${{ inputs.unitTestInput }}" == true ]; then
            echo "json=$SUM" >> "$GITHUB_ENV"
          elif [ "${{ inputs.unitTestInput }}" == true ]; then
            echo "json=${{vars.UT_INSTANCE_COUNT}}" >> "$GITHUB_ENV"
          elif [ "${{ inputs.cypressInput }}" == true ]; then
            echo "json=${{vars.CYPRESS_INSTANCE_COUNT}}" >> "$GITHUB_ENV"
          else
            echo json=$SUM >> "$GITHUB_OUTPUT"
          fi

  my_job-1:
    runs-on: ubuntu-latest
    environment: test
    needs: my_job
    steps:
      - name: Echo Value
        run: echo ${{ needs.my_job.outputs.json }}
