name: test-github-Actions
on: push
jobs:
  job-1:
    if: ${{github.event_name != 'schedule' || github.ref_name != 'master'}}
    runs-on: ubuntu-latest
    steps:
      - name: print the value  - Job-1
        run: echo "This is 1st Job"
  job-2:
    needs: job-1
    runs-on: ubuntu-latest
    steps:
      - name: print the value - Job-2
        run: echo "This is 2nd Job"
      - name: Branch Name
        run: echo Branch Name ${{ github.ref_name }}
  job-3:
    needs: job-2
    runs-on: ubuntu-latest
    steps:
      - name: print the value - Job-3
        run: echo "This is 3rd Job"
